apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: helloworld-call-
spec:
  entrypoint: helloworld
  templates:
    - name: helloworld
      steps:
        - - name: echo-helloworld
            template: echo
            arguments:
              parameters:
              - name: msg
                value: "hello, zhulei"
    - name: "echo"
      inputs:
        parameters:
          - name: msg
      container:
        image: busybox
        command:
          - "echo"
        args:
          - "{{inputs.parameters.msg}}"
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
