apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: s3-workflow-template
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: echo
        templateRef:
          name: helloworld-tmpl
          template: echo
        arguments:
          parameters:
            - name: msg
              value: "s3-workflow-template"